name: Validate Pull Request

on:
  repository_dispatch:
    types: [create-pull-request]
  pull_request:
    branches:
      - production
      - staging
      - develop

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch for production
        if: github.event.pull_request.base.ref == 'production'
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ "$SOURCE_BRANCH" != "staging" && "$SOURCE_BRANCH" != hot-fix/* ]]; then
            echo "Pull requests to 'production' must come from 'staging' or 'hot-fix/*' branches."
            exit 1
          fi

      - name: Check source branch for staging
        if: github.event.pull_request.base.ref == 'staging'
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ "$SOURCE_BRANCH" != "develop" ]]; then
            echo "Pull requests to 'staging' must come from 'develop' branch."
            exit 1
          fi

      - name: Check source branch for develop
        if: github.event.pull_request.base.ref == 'develop'
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ "$SOURCE_BRANCH" != feature/* && "$SOURCE_BRANCH" != hot-fix/* && "$SOURCE_BRANCH" != bug-fix/* ]]; then
            echo "Pull requests to 'develop' must come from 'feature/*', 'hot-fix/*', or 'bug-fix/*' branches."
            exit 1
          fi