name: 'Check staging branch PR'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check staging branch
        if: github.base_ref == 'staging' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to staging from dev."
          exit 1
      - name: Check production branch
        if: github.base_ref == 'production' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to production from staging."
          exit 1