name: Create Staging PR

# Should this be instead on build success for image?
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - develop

jobs:
  build_base_image:
    name: Auth, Build Latest, Tag, Push
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      # https://cli.github.com/manual/gh_pr
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          output=$(gh pr create --base staging --head develop --title 'Auto PR' --body 'Auto PR test' 2>&1)
          status=$?

          if [ $status -ne 0 ]; then
            if echo "$output" | grep -q "https://github.com/"; then
              echo "$output"
              exit 0
            else
              echo "$output"
              exit $status
            fi
          else
            echo "$output"
          fi