name: Create Draft Release

# This needs to be triggered when the draft release is created
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - staging

jobs:
  create_draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      
      # This grep command looks for the first instance of a version tag with the assumption that the first instance
      # represents the version of the project itself rather than a dependency version.
      - name: Extract version tag from pyproject.toml
        run: |-
          pwd
          grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o
          echo "PYPROJECT_VERSION=`grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o`" >> $GITHUB_ENV
      
      # https://cli.github.com/manual/gh_release
      - name: Create draft release via CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh release create "v${PYPROJECT_VERSION}-rc" \
          --prerelease \
          --target staging \
          --generate-notes
