name: Create Draft Release

# This needs to be triggered when the draft release is created
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - staging

jobs:
  create_draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      
      # This grep command looks for the first instance of a version tag with the assumption that the first instance
      # represents the version of the project itself rather than a dependency version.
      # Note that the `-P` flag in the piped `grep` call is specific to the version that is available on the ubuntu-latest
      # runners, which is different than what is generally available by default on OSX, which uses `-e`. 
      - name: Extract version tag from pyproject.toml
        run: |-
          echo "PYPROJECT_VERSION=$(grep -m 1 version pyproject.toml | grep -P '\d.\d.\d' -o)" >> $GITHUB_ENV
      
      # https://cli.github.com/manual/gh_release
      - name: Create draft release via CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh release create "v${PYPROJECT_VERSION}-rc" \
            --prerelease \
            --target staging \
            --generate-notes \
            --title v${PYPROJECT_VERSION}-rc
